export const CHOCOLATES = [
    { id: "C1", themes: ["Mischief", "Nostalgia"] },
    { id: "C2", themes: ["Protection", "Admiration"] },
    { id: "C3", themes: ["Nostalgia", "Growth"] },
    { id: "C4", themes: ["Rivalry", "Sweetness"] },
    { id: "C5", themes: ["Mischief", "Rivalry"] },
    { id: "C6", themes: ["Sweetness", "Dependence"] },
    { id: "C7", themes: ["Growth", "Protection"] },
    { id: "C8", themes: ["Admiration", "Nostalgia"] },
    { id: "C9", themes: ["Mischief", "Protection"] },
    { id: "C10", themes: ["Sweetness", "Growth"] },
    { id: "C11", themes: ["Nostalgia", "Sweetness"] },
    { id: "C12", themes: ["Admiration", "Mischief"] },
    { id: "C13", themes: ["Dependence", "Growth"] },
    { id: "C14", themes: ["Rivalry", "Protection"] },
    { id: "C15", themes: ["Mischief", "Dependence"] },
    { id: "C16", themes: ["Admiration", "Sweetness"] },
    { id: "C17", themes: ["Growth", "Rivalry"] },
    { id: "C18", themes: ["Protection", "Nostalgia"] },
    { id: "C19", themes: ["Sweetness", "Admiration"] },
    { id: "C20", themes: ["Mischief", "Growth"] },
];